### ISSUE TITLE
TypeError: connected() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by proft** [hharnisc/python-meteor#32]
Hi!

I have meteor 1.4.0.1 and python 2.7 and python-meteor 0.1.6.

My code is 

```
import time
from MeteorClient import MeteorClient

client = MeteorClient('ws://127.0.0.1:3000/websocket')

def connected(self):
    print('* CONNECTED')
def subscribed(subscription):
    print('* SUBSCRIBED {}'.format(subscription))
client.on('connected', connected)
client.on('subscribed', subscribed)

client.connect()

client.subscribe('messages')
client.unsubscribe('messages')
```

Error is 

```
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/ws4py/websocket.py", line 506, in run
    if not self.once():
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/DDPClient.py", line 53, in once
    return super(DDPSocket, self).once()
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/ws4py/websocket.py", line 388, in once
    if not self.process(b):
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/ws4py/websocket.py", line 458, in process
    self.received_message(s.message)
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/DDPClient.py", line 41, in received_message
    self.emit('received_message', data)
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/pyee/__init__.py", line 117, in emit
    f(*args, **kwargs)
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/DDPClient.py", line 179, in received_message
    self.emit('connected')
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/pyee/__init__.py", line 117, in emit
    f(*args, **kwargs)
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/MeteorClient.py", line 316, in connected
    self.emit('connected')
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/pyee/__init__.py", line 117, in emit
    f(*args, **kwargs)
TypeError: connected() takes exactly 1 argument (0 given)

Traceback (most recent call last):
  File "d.py", line 16, in <module>
    client.subscribe('messages')
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/MeteorClient.py", line 201, in subscribe
    self._wait_for_connect()
  File "/home/proft/.virtualenvs/testddb/lib/python2.7/site-packages/MeteorClient.py", line 356, in _wait_for_connect
    raise MeteorClientException('Could not subscribe because a connection has not been established')
MeteorClient.MeteorClientException: Could not subscribe because a connection has not been established
```

Why it is broken? Because of 1.4 version of meteor?

**Comment by proft** [comment]
Tested on 1.4.0.1 and 1.3.3.1.

**Comment by proft** [comment]
The same error with meteor 1.2.1.

**Comment by proft** [comment]
Solved. I have recreated virtual environment ... strange but it's true).
